BA_GRAPH_PATH = ...
CFLAGS = -std=c++17 -fconcepts -I$(BA_GRAPH_PATH)/include
LDFLAGS = -lstdc++fs
DBGFLAGS = -g -O0 -pedantic
COMPILE_DBG = $(CXX) $(CFLAGS) $(DBGFLAGS)


copy_implementation:
	cp $(BA_GRAPH_PATH)/test/implementation_basic.h implementation.h
all: copy_implementation compile_main
compile_main:
	$(COMPILE_DBG) main.cpp -o c_main.out $(LDFLAGS)

clean:
	rm -rf *.out

.PHONY: clean all compile_main copy_implementation
